### ISSUE TITLE
SourceSection equality

### ISSUE THREAD

**Issue by mlvdv** [graalvm/truffle#100]
SourceSection Javadoc does not say how equality/hash are defined, especially so with respect to associated tags.

**Comment by chumer** [comment]
I have to admit that tags on source sections is not a very nice solution. I want to revisit this still.

**Comment by chumer** [comment]
Tags in SourceSections are gone now. Anything else we need to define?

**Comment by chumer** [comment]
Please close if not.

**Comment by mlvdv** [comment]
SourceSection Javadoc still does not say how equality/hash are defined.
