### ISSUE TITLE
Documentation for iterateFrames() is misleading

### ISSUE THREAD

**Issue by eregon** [graalvm/truffle#106]
From @chrisseaton  and 7d1f40518422ad17164dff1b065a2efdb6e489e7, `iterateFrames()` now iterates the topmost frame instance, that is the frame instance returned by `getCurrentFrame()`.
If that is the case, it seems very important to fix the javadoc which states the [opposite](https://github.com/graalvm/truffle/blob/master/truffle/com.oracle.truffle.api/src/com/oracle/truffle/api/TruffleRuntime.java#L149-L151).

**Comment by chumer** [comment]
Thanks for fixing this.
