### ISSUE TITLE
Debugger requirement:  terminate guest language execution immediately

### ISSUE THREAD

**Issue by mlvdv** [graalvm/truffle#109]
The Debugger currently halts execution by throwing a `KillException`, which unwinds immediately all instrumentation and guest language execution code through the original call, e.g. `PolyglotEngine.eval()`.  Language implementations must now support this by ensuring that the exception is correctly passed through any `catch`.

@chumer suggests replacing this implementation with something more general that does not depend on the language implementations for correctness.

Note: The Debugger also uses the `QuitException`, which requires exactly the same support.  Only one kind of exception is actually required, so support for `QuitException` is not a separate requirement.

**Comment by woess** [comment]
Since the exceptions are part of the API I suggest to resolve this issue before the next truffle release.

**Comment by mlvdv** [comment]
+1

**Comment by jtulach** [comment]
As Martin @entlicher points out in https://github.com/graalvm/truffle/pull/98#issuecomment-196414431 try to use internal `ThreadDeath` subclass.

**Comment by woess** [comment]
@jtulach @entlicher This sounds like a bad idea. `ThreadDeath` should always be rethrown if it's caught. We catch `KillException` in a few places.

**Comment by entlicher** [comment]
I still do not see a problem.
Everyone who see it as a ThreadDeath should rethrow it. (Language implementors)
Everyone who see it as a KillException (which extends ThreadDeath) can swallow it. (Truffle infrastructure, debugger, etc.)

**Comment by woess** [comment]
Oh, sorry, I misunderstood. I see your point now. Yes that's fine if the KillException is not exposed as API.

**Comment by jtulach** [comment]
Martin's idea is now expressed in #140
