### ISSUE TITLE
Redundant Travis checks.

### ISSUE THREAD

**Issue by zapster** [graalvm/truffle#127]
In Travis we execute 
- `mx checkoverlap`
- `mx canonicalizeprojects`
- `mx checkstyle`
- `sh .travis.sigtest.sh`

as separate tasks but these are also part of  `mx gate --strict-mode`:
- `Distribution Overlap Check`
- `Canonicalization Check`
- `Checkstyle`
- `Truffle Signature Tests`

In **graal-core** we use `mx gate --tags` to implement non-redundant parallel gates (see graalvm/graal-core#17).

**Comment by zapster** [comment]
quickfix: remove redundant Travis tasks to avoid spawning useless jobs.

**Comment by chumer** [comment]
Not relevant anymore as we don't use Travis for CI anymore.
