### ISSUE TITLE
DSL generating wrong type for @Cached

### ISSUE THREAD

**Issue by nirvdrum** [graalvm/truffle#151]
If the type used in a @Cached entry requires qualification, the DSL truncates after the `.` and ends up generating the wrong type.

E.g., I have the following:

```
@Specialization(guards = { "!isEmpty(string)", "isSingleByteOptimizable(string)" })
public int ordAsciiOnly(DynamicObject string,
      @Cached("create(getContext(), getSourceSection())") RopeNodes.GetByteNode getByteNode) {
...
}
```

The  generated class for this specialization ends up looking like:

```
@GeneratedBy(methodName = "ordAsciiOnly(DynamicObject, GetByteNode)", value = OrdNode.class)
private static final class OrdAsciiOnlyNode_ extends BaseNode_ {

  @Child private org.jruby.truffle.core.rope.RopeNodes getByteNode;

   ....
}
```

Note that the @Child field is of type `RopeNodes` rather than `RopeNodes.GetByteNode`.

**Comment by chumer** [comment]
@nirvdrum  thanks for the report looks like a bug.
I guess you can workaround this easily so its not blocking you?

**Comment by chumer** [comment]
The workaround would be to not use ambiguous type names.

**Comment by nirvdrum** [comment]
The work around I used was to use an explicit @Child field and skip use of @Cached in these instances. I could also rename the nodes, but they correspond to different types and logically map to method names on those types.

**Comment by chumer** [comment]
Continued elsewhere: GR-1082
