### ISSUE TITLE
Insufficient synchronization in InstrumentationHandler

### ISSUE THREAD

**Issue by entlicher** [graalvm/truffle#154]
Introduction of `Debugger.pause()` (see [the pull request #153](https://github.com/graalvm/truffle/pull/153)), revealed insufficient synchronization of code operating on `roots` map and `bindings` list.
`roots` is a synchronized map, but there are several unsynchronized iterations over it's key set. This leads to `ConcurrentModificationException`.

Bindings can be added asynchronously at any time while a language is executed. This is the case for e.g. debugger breakpoints and debugger pause. That means that `bindings` list can be changed at any time. This makes the code in `AbstractBindingsVisitor` problematic, `shouldVisit()` might not use the same list of elements as `visit(Node)` and there is a risk of `IndexOutOfBoundsException` when e.g. breakpoint is removed - one binding is removed.

The similar lack of synchronization may apply to `instrumenterMap` map.

**Comment by chumer** [comment]
This is now fixed. The instrumentation API is fully thread-safe including the instrumenterMap.
