### ISSUE TITLE
Debugger requirement: language-specific display of values

### ISSUE THREAD

**Issue by mlvdv** [graalvm/truffle#155]
The debugger needs access to language-specific textual display of language values.  This was formerly supported by the (now deprecated):
     `String TruffleLanugage.getVisualizer().displayValue(Object value, int trim)`

The REPL debugger now uses `Object.toString()`.

@mickjordan reports that this is important for current work.

**Comment by chumer** [comment]
New method TruffleLanguage#toString got integrated and is used by the debugger.
