### ISSUE TITLE
Debugger requirement:  language-specific frame hiding

### ISSUE THREAD

**Issue by mlvdv** [graalvm/truffle#156]
The debugger needs to decide which stack frames to display, for example in a backtrace, during normal debugging.  What's needed is a language-specific recommendation on whether any given frame would be sensible (useful) to a guest language programmer.

The debugger might display such frames anyway, for example in a special mode for language implementors.

**To discuss**:  should the recommendation that a particular frame be hidden also be treated as a suggestion that the call-site that created the frame also be hidden?  I'm thinking of Ruby's implementation of certain (but not all) looping constructs as calls.  I specifically hid those calls in an early debugger prototype.

@mickjordan reports that this would be useful for current work

**Comment by entlicher** [comment]
In the past there was a suggestion to add a `FrameFormat` interface, which could be passed in through `FrameDescriptor` and that could have something like `String getTraceLine()`. That could return `null` for hidden frames.
But an idea with an introduction of `CapabilityProvider` suggested in issue #157 could solve this in an evolvable way...

**Comment by mlvdv** [comment]
I like the `CapabilityProvider` idea.  

I would avoid `String getTraceLine()` for two reasons:
- client should have the option to display hidden frames
- client should be able to create tool-specific formatting of provided information

Language capability for displaying information should be restricted only to primitive things, e.g. values, names.

**Comment by chumer** [comment]
Tracked elsewhere: GR-88
