### ISSUE TITLE
Interop semantics with immutable types

### ISSUE THREAD

**Issue by lukasstadler** [graalvm/truffle#160]
Some languages, like R, have immutable data types, but allow modifications by using value semantics for updates.
An example:
```R
x <- list(a=1) # creates a new list with element "a" == 1 and assigns it to variable x
x$b <- 2 # adds an element "b" == 2
```
While the second statement seems to modify the list, it doesn't: the parser desugars this into the following statement:
```R
x <- `$<-`(x, "b", 2)
```
The call to the update function `$<-` returns a new list with the original "a" field and the new "b" field.
In cases like this one, where it does not influence language semantics, the runtime can modify the list, but this is only an internal optimization and not something that can be exposed to language users.

What should happen when other languages try to change an immutable data structure?
I see three options:
1) Prevent any modifications from other languages; immutable data structures simply do not understand the write message.
2) Allow modifications from other languages. This will lead to unexpected and undeterministic behavior in the original language.
3) Implement some clever copy-on-write scheme that keeps a copy of the original data, but allows for modifications (which are then only visible in other languages).

I think that 1) is the correct solution: if other languages want to modify the data, they need to copy it into their own, modifiable, data structures.

/cc @jtulach @smarr @chumer

**Comment by grimmerm** [comment]
I completely agree with @lukasstadler, IMHO option 1) is the most reasonable thing to do.
In general, I think it's better to build a system thats easy, understandable, but more restrictive than building a system that can do fancy things but it is hard to get things right.

**Comment by ldaynes** [comment]
I agree too.

**Comment by chumer** [comment]
I see also option 4)
Every interop write must be integrated in a way so it potentially does a copy. So write messages potentially return a new object that needs to be reassigned in the other language. For mutable objects it returns the same object.

This would mean that if you write into an RList from JavaScript
```js
rlist = ... // rlist coming from rcode
rlist[2] = 3 // does actually copy rlist
```

What do you guys think?

Of course 1) would be easier and potentially evolvable into 4).

**Comment by lukasstadler** [comment]
It would be easy to support 4) from the POV of languages that already have immutable types.
Other languages, e.g., JS, would need serious implementation effort to support this, especially for complex expressions like `x[i].a.b = 5`.

**Comment by chumer** [comment]
Good point. I just wanted to bring it up. Option 1) is probably good enough for now.

**Comment by lukasstadler** [comment]
ok, then we'll go with 1) for now, please reopen if things change.

**Comment by woess** [comment]
I think immutable objects with copy-on-write semantics could be encapsulated in mutable wrapper objects for languages like JS, etc.
