### ISSUE TITLE
0.13-SNAPSHOT of truffle-dsl-processor not published

### ISSUE THREAD

**Issue by pniederw** [graalvm/truffle#173]
http://lafo.ssw.uni-linz.ac.at/nexus/content/repositories/repos-public/com/oracle/truffle/truffle-dsl-processor/ only has 0.12-SNAPSHOT, whereas other modules (e.g. http://lafo.ssw.uni-linz.ac.at/nexus/content/repositories/repos-public/com/oracle/truffle/truffle-api/) have 0.13-SNAPSHOT.

`mx maven-install` does produce a 0.13-SNAPSHOT:

```
[INFO] Installing /xxx/truffle/mxbuild/dists/truffle-dsl-processor.jar to /xxx/.m2/repository/com/oracle/truffle/truffle-dsl-processor/0.13-SNAPSHOT/truffle-dsl-processor-0.13-SNAPSHOT.jar
```

**Comment by smarr** [comment]
I suspect @jtulach or @gilles-duboscq could know more about that. Guys?

**Comment by jtulach** [comment]
I don't know anything about it.
