### ISSUE TITLE
`InstrumentationHandler.visitRoot(.)` seems not thread safe

### ISSUE THREAD

**Issue by smarr** [graalvm/truffle#180]
The `InstrumentationHandler.visitRoot()` method sets fields of an `AbstractNodeVisitor` (`root` and `providedTags`), at the end, it sets the fields to `null`.

This seems thread-unsafe. Considering `InstrumentationHandler.installRootNode()` calls `visitRoot()` with the `addAllBindingsVisitor`, this seems to be unsafe, because multiple threads can end up using the same instance of `addAllBindingsVisitor` object, and mutating it unsynchronized.

This seems to be introduced with https://github.com/graalvm/truffle/commit/2aa2eff1c157c847cae58734075a57fd14c0acb9

/cc @mlvdv

**Comment by smarr** [comment]
My work-around for the moment is to synchronize on the visitor object, see: https://github.com/smarr/truffle/commit/2ff534e72701807ce7d0fe50894092762ba0eb2d

**Comment by chumer** [comment]
You are totally right. Will fix that. I also need to add quite some tests.

**Comment by chumer** [comment]
Fixed in the latest revision. Node visitors are not resued anymore and the rest of the methods should be thread-safe as well.
