### ISSUE TITLE
Make `@NodeInfo` annotation `@Inherited`

### ISSUE THREAD

**Issue by pniederw** [graalvm/truffle#182]
I think that `@NodeInfo` should be `@Inherited`, to make it easier to retrieve from node subclasses (e.g. those generated by Truffle codegen).

**Comment by chumer** [comment]
Good idea! Will fix.

**Comment by chumer** [comment]
Fixed: https://github.com/graalvm/truffle/commit/5089a017651e26771827f0e8a02388a6fde6d7bd
