### ISSUE TITLE
Range check in Source#createSection is off by one (rejects good code)

### ISSUE THREAD

**Issue by pniederw** [graalvm/truffle#184]
``` java
import com.oracle.truffle.api.source.Source;

// works as expected, prints:
// source=test pos=5 len=0 line=1 col=6 identifier=test code=
System.out.println(Source.fromText("12345", "test").createSection("test", 1, 6, 5, 0));

// fails unexpectedly with:
// java.lang.IllegalArgumentException: column out of range
// the "out of range" check seems to be off by 1
System.out.println(Source.fromText("12345", "test").createSection("test", 1, 6, 0));
```

**Comment by pniederw** [comment]
Anyone? I hope this one is not too vague. :-)

**Comment by mlvdv** [comment]
Not at all vague; thanks for the clear tests.

The exception thrown by the second example is correct; there is no column 6 in the test code, so this position is out of range.  Text coordinates in these interfaces are based on character positions, not the position between two characters.  Only positions 1 through 5 are legitimate for this source.

The first example may work partially, but the SourceSection is in an internally inconsistent state.  The method arguments are incorrect, but this method (as documented) does not check arguments.  This method supports parsers that pre-compute both characters offsets and row/column positions, which avoids having to recompute them.  It is best avoided for other use cases.

**Comment by pniederw** [comment]
I see. The fact that only one of the two methods checks its arguments led me to the wrong conclusion.

It's important to me that I can have such a source section. I use it to represent the source location of parse errors of the kind "something is missing at the end of the input". I guess I'll just keep using the first method for now.

**Comment by mlvdv** [comment]
Agreed that this coordinate system does not permit a legitimate SourceSection that points beyond the contents of the Source.  The best approximation that is internally consistent would be one that points at the final character (which might be a newline).
