### ISSUE TITLE
Is `Source#withName` etc. accidentally non-public?

### ISSUE THREAD

**Issue by pniederw** [graalvm/truffle#186]
Are methods `withName`, `withShortName`, and `withPath` supposed to be public rather than package-private?

Javadoc of `withPath` should probably say "..with the specified path" rather than "...with the specified short name".

**Comment by jtulach** [comment]
They will be deleted and replaced by `Source.Builder`. See the work in https://github.com/jtulach/truffle/tree/SourceBuilder

**Comment by chumer** [comment]
SourceBuilder got integrated. Closing issue.
