### ISSUE TITLE
Mixed up Javadoc for @TypeCheck and @TypeCast

### ISSUE THREAD

**Issue by pniederw** [graalvm/truffle#194]
Truffle 0.14

From `TypeCheck`'s Javadoc:

Is:
> This is useful for types where the guest language specific type check can be implemented more efficiently than a direct cast.

Should be:
> This is useful for types where the guest language specific type check can be implemented more efficiently than an instanceof check.

From `TypeCast`'s Javadoc:

Is:
> This is useful for types where the guest language specific type cast can be implemented more efficiently than an instanceof check.

Should be:
> This is useful for types where the guest language specific type cast can be implemented more efficiently than a direct cast.

**Comment by chumer** [comment]
Will fix. Thanks.

**Comment by chumer** [comment]
Fixed: https://github.com/graalvm/truffle/commit/efc7310c40c6bb68bc8a12cb4b3a439ac78f74e1
