### ISSUE TITLE
Make Source.Builder.path(String) public

### ISSUE THREAD

**Issue by pniederw** [graalvm/truffle#199]
For the same reason that `name`, `uri` and `mimeType` can be configured explicitly, `path` should be explicitly configurable as well.

**Comment by jtulach** [comment]
Possible, or as an option deprecate remove `Source.getPath()` what it is good for anyway?

**Comment by pniederw** [comment]
Just like it can be useful to get the `URL` a `Source` was loaded from, it can be useful to get the file path it was loaded from, as long as `getPath()` only returns non-null if loaded from a file (or explicitly set). Because I couldn't get earlier versions of `Source` to behave consistently in this regard, I had to retain this information by associating each `Source` with an object of my own that tells how the `Source` was constructed. However, this breaks down in certain cases, e.g. when the `Source` has not been constructed by my own code (think polyglot).

**Comment by jtulach** [comment]
The same information should be available from the [getURI](http://lafo.ssw.uni-linz.ac.at/javadoc/truffle/latest/com/oracle/truffle/api/source/Source.html#getURI--)() method:
```
if (source.getURI().getScheme().equals("file")) {
  File f = new File(source.getURI());
}
```
We want to use `getURI()` as a persistent identification of source. Thus I recommend to rely on that one rather than using `getPath()` which doesn't have any real meaning (as far as I can tell) and I'd like to get rid of it, if possible.

**Comment by pniederw** [comment]
@jtulach That's pretty much what I ended up with. Do you also plan to get rid of `getURL()`?

**Comment by jtulach** [comment]
Right. That method seems really obsolete now when there is `getURI()`.

**Comment by pniederw** [comment]
For my language, it makes a difference whether a `Source` has been loaded from a file or (possibly a file://) URL. However, I'm keeping track of this on my own, and have given up on the idea that I can deduce this from `Source`. Hence, having `getPath()` and `getURL()` is no longer essential to me. Closing.
