### ISSUE TITLE
Redesign SourceSection API and implementation

### ISSUE THREAD

**Issue by mlvdv** [graalvm/truffle#52]
`SourceSection` is old prototype code and is overdue for redesign and reimplementation.  One goal is to reduce memory footprint. There are also open issues around requirements for variants that carry useful information when actual source is either unavailable or nonexistent; this is especially important for tools.  Among others, a representative of each language team should be included in a discussion of requirements for "unavailable" as well as any other requirements that experience has revealed.

**Comment by jtulach** [comment]
While the origin of the code may be a prototype, I'd like to point of that Javadoc of both truffle@0.10 and truffle@0.11 include the package in *stable* API category.
