### ISSUE TITLE
Need a simple way to restrict a SourceSectionFilter to a specific AST root (nested functions)

### ISSUE THREAD

**Issue by mickjordan** [graalvm/truffle#80]
For languages that allow a function to contain lexically nested functions, e.g. R, there needs to be an easy way to restrict a SourceSectionFilter to the body of the enclosing function but excluding the bodies of the nested functions. The indexIn method for the outer function (which must be used to uniquely identify the function in the face if duplicates in the "same" source") necessarily includes the bodies of the nested functions. The consequence is that, .e.g. a debugger will step into the bodies of nested functions when it should step over because the filter will match statements in the nested functions. Generating a list of indexNotIn filters would be possible but tedious.

**Comment by mlvdv** [comment]
Good issue; I can see other situations where this flexibility will be needed. 
I agree that `indexNotIn(SourceSection)` filters would be tedious, but this might be the simplest and most clear API.  Client code would start a build and iterate over each nested `SourceSection` adding that filter expression.  The internal representation, of course could be transformed for fast matching.

**Comment by chumer** [comment]
PR got integrated. Seems to be adopted. Closing.
